language: node_js
sudo: required
node_js:
  - 10
cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn install

script:
  - yarn build
  - cd ./vuepress && touch CNAME && echo 'awesome-see.com' > CNAME && cd ..

deploy:
  provider: pages
  email: upcwangying@126.com
  name: upcwangying
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: vuepress
